version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nexus
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nexus
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery:
    build: .
    command: celery -A nexus.application.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nexus
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - app
      - redis
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A nexus.application.tasks.celery_app beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nexus
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - app
      - redis
    restart: unless-stopped

  flower:
    build: .
    command: celery -A nexus.application.tasks.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nexus
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - app
      - redis
      - celery
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
